apiVersion: apps/v1
kind: Deployment
metadata:
  name: mykube
  labels:
    app: movies
spec:
  replicas: 3
  selector:
    matchLabels:
      app: movies
  template:
    metadata:
      labels:
        app: movies
    spec:
      containers:
      - name: mykube
        image: mwolski22/movie_app
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mykube
spec:
  selector:
    app: movies
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
